Start local
greenpress/greenpress-cli pull request #17
Opened 2020-08-31 07:54 UTC by drorrose

Added local option to start command and updated readme accordingly

2020-08-31 10:55 UTC, davidmeirlevy requested changes

2020-08-31 10:55 UTC, davidmeirlevy commented on commands/start.js
> +async function LocalizeRequestedServices(services) {
a function cannot start with capital letter if it's not a class.

2020-08-31 10:55 UTC, davidmeirlevy commented on commands/start.js
> +			process.env.AUTH_SERVICE_CWD = process.cwd() + '/dev/' + service;
seems liks something you can create a function to avoid copy-pasting.

2020-08-31 10:55 UTC, davidmeirlevy commented on commands/start.js
> +		switch(service)
if the values are known and it's an array, create an array of known values and results, and iterate your array instead of the given array.

2020-08-31 13:33 UTC, drorrose commented on commands/start.js
> +async function LocalizeRequestedServices(services) {
Removed

2020-08-31 13:33 UTC, drorrose commented on commands/start.js
> +			process.env.AUTH_SERVICE_CWD = process.cwd() + '/dev/' + service;
Taken care of

2020-08-31 13:34 UTC, drorrose commented on commands/start.js
> +		switch(service)
I implemented it as a const object instead of an associative array, seemed simpler..

2020-08-31 13:35 UTC, drorrose commented
Fixed code following review, check it out :)

2020-09-01 18:39 UTC, davidmeirlevy requested changes

2020-09-01 18:39 UTC, davidmeirlevy commented on commands/start.js
> +const servicesEnvs = {
This can’t work.. you should store the keys themselves, not the actual values.

2020-09-03 18:25 UTC, drorrose commented on commands/start.js
> +const servicesEnvs = {
Done

2020-09-04 04:59 UTC, davidmeirlevy requested changes

2020-09-04 04:59 UTC, davidmeirlevy commented on commands/start.js
> +	'authentication-service': 'process.env.AUTH_SERVICE_CWD',
You should store only the key, without the “process.env”.

2020-09-04 05:24 UTC, drorrose commented on commands/start.js
> +	'authentication-service': 'process.env.AUTH_SERVICE_CWD',
sorry, forgot to delete it...now it should be done

2020-09-04 07:55 UTC, davidmeirlevy requested changes

2020-09-04 07:55 UTC, davidmeirlevy commented on commands/start.js
> +				for (const service of options.local.split(',')) {
It can’t match, because you expect users to enter services names (admin, auth, content..) and not repositories names (admin-panel, authentication-service, content-service..)

2020-09-04 20:38 UTC, drorrose commented on commands/start.js
> +				for (const service of options.local.split(',')) {
I changed the expected input of services name, but I left admin-panel and blog-front as is since it seemed more fluent that way. If you want to change it up, let me know and I'll do so.

2020-09-05 06:44 UTC, davidmeirlevy approved these changes

2020-09-05 06:44 UTC, davidmeirlevy commented on commands/start.js
> +						exit(1)
"process" is a global variable in node, you don't need to require it.
but it's ok..

2020-09-05 06:46 UTC, davidmeirlevy commented
you need to rebase your branch. Itay added a change for colorized console messages.
it will be nice to add those colors to this feature too.

2020-09-05 10:03 UTC, drorrose commented on commands/start.js
> +						exit(1)
without this require I had an UnhandledPromiseRejectionWarning when encountering the exit (for invalid input).

2020-09-05 10:50 UTC, davidmeirlevy approved these changes

2020-09-05 11:36 UTC, merged