added theme command. added possible values to help of service create
greenpress/greenpress-cli pull request #43
Opened 2020-11-04 16:59 UTC by drorrose

2020-11-04 20:06 UTC, davidmeirlevy requested changes

2020-11-04 20:06 UTC, davidmeirlevy commented on services/theme.js
> +				theme: 'global:' + path.join(process.cwd(), 'themes', ${name})
The name is a string. Should be quoted.

2020-11-04 20:52 UTC, drorrose commented on services/theme.js
> +				theme: 'global:' + path.join(process.cwd(), 'themes', ${name})
Right, fixed it

2020-11-05 08:47 UTC, davidmeirlevy approved these changes

2020-11-05 20:01 UTC, merged