Deploy to Heroku!
greenpress/greenpress-cli pull request #54
Opened 2021-01-26 19:28 UTC by davidmeirlevy

2021-01-27 21:36 UTC, drorrose requested changes

2021-01-27 21:36 UTC, drorrose commented on commands/deploy.js
> +		.description('deploy of Greenpress to one of the supported clouds: heroku')
would have created a const array of supported cloud services instead of hard coding it to the description

2021-01-27 21:36 UTC, drorrose commented on commands/deployment.js
> +		.description('create a new deploy of Greenpress to one of the supported clouds: heroku')
the array from the comment in deploy applys here. would put this array in a utility so both deploy and deployment will be able to use it

2021-01-27 21:36 UTC, drorrose commented on commands/deploy.js
> +		.description('deploy of Greenpress to one of the supported clouds: heroku')
would have created a const array of supported cloud services instead of hard coding it to the description

2021-01-27 21:36 UTC, drorrose commented on controllers/deploy.js
> +const execute = require('../utils/execute');
there are many things that are unused in this file and should be removed

2021-01-27 21:36 UTC, drorrose commented on controllers/deploy.js
> +	await execute(`git push heroku master -f`, 'deploy to heroku', { stdio: 'inherit' });
do we really want this action to force the user to open another terminal? not sure that this studio:inherit is so user friendly in this case

2021-01-27 21:36 UTC, drorrose commented on controllers/deployment.js
> +	if (!await execute('heroku login', 'login to heroku')) {
are we sticking to the assumption that the user must manually login first? if not, this line here should always fail! what about passing an auth token here?

2021-01-27 21:36 UTC, drorrose commented on controllers/deployment.js
> +			console.log(red(`failed to install ${key} to ${appName}`));
failed to instal key in appname, not to

2021-01-27 21:36 UTC, drorrose commented on controllers/deployment.js
> +	const mongoUri = (await askQuestion('what is your mongo URI:', '')) || '';
Wouldn't it be more user friendly to allow a default of a specific env variable?

2021-01-27 21:36 UTC, drorrose commented on controllers/populateHeroku.js
> +const askQuestion = require('../utils/question');
I currently don't see any use to this controller (in this PR). shouldn't you create a command that utilizes it? if so, shouldn't it accept app name (on heroku)?

2021-01-28 05:39 UTC, davidmeirlevy commented on controllers/deploy.js
> +	await execute(`git push heroku master -f`, 'deploy to heroku', { stdio: 'inherit' });
This push to heroku with git displays the build logs of heroku. We want to show it in deploy.

2021-01-28 05:40 UTC, davidmeirlevy commented on controllers/deployment.js
> +	if (!await execute('heroku login', 'login to heroku')) {
The token case will be implemented in the next phase.

2021-01-28 05:41 UTC, davidmeirlevy commented on controllers/deployment.js
> +	const mongoUri = (await askQuestion('what is your mongo URI:', '')) || '';
What do you mean?

2021-01-28 05:42 UTC, davidmeirlevy commented on controllers/populateHeroku.js
> +const askQuestion = require('../utils/question');
Should be removed. You’re right.

2021-01-28 15:04 UTC, drorrose commented on controllers/deploy.js
> +	await execute(`git push heroku master -f`, 'deploy to heroku', { stdio: 'inherit' });
Ok cool. How about providing an option to write stdio to a file?

2021-01-28 15:07 UTC, drorrose commented on controllers/deployment.js
> +	if (!await execute('heroku login', 'login to heroku')) {
Sound legit, but in that case (and if we want to put this version on npm) I think the error message should contain some indication for the user that for now they should login manually to heroku cli prior to running this command again

2021-01-28 15:11 UTC, drorrose commented on controllers/deployment.js
> +	const mongoUri = (await askQuestion('what is your mongo URI:', '')) || '';
You used an empty string as default. I would have allow the user to set the uri in an env variable, so if they don't want to input the uri when asked, we would assign the variable's value. Something along: const mongoUri = (await question ('whats your uri?", Process.env.Heroku_mongo_uri | ''))

2021-01-28 18:01 UTC, davidmeirlevy commented on controllers/deploy.js
> +	await execute(`git push heroku master -f`, 'deploy to heroku', { stdio: 'inherit' });
Nice idea. Second phase :)

2021-01-28 18:03 UTC, davidmeirlevy commented on controllers/deployment.js
> +	const mongoUri = (await askQuestion('what is your mongo URI:', '')) || '';
Oh ok. Nice idea.

2021-02-01 17:56 UTC, drorrose requested changes
@davidmeirlevy @lironshabtai 
Basically approved, but I would like to hear what you think about this issue with the URI...

2021-02-01 17:56 UTC, drorrose commented on commands/deployment.js
> +		.option('-mg, --mongo <mongo>', 'MongoDB URI')
still requires a lot of manual typing, unless you pass it in a manner similar to:
greenpress deployment --mongo=$MONGO_URI

wouldn't it be better to use an env variable instead? anyhow, way better than the last iteration :)

2021-02-01 17:56 UTC, drorrose commented on controllers/deployment/heroku.js
> +async function deployHeroku({ mongo }) {
cool usage, we should adapt it to all of the other commands that utilize the options struct

2021-02-02 08:33 UTC, davidmeirlevy commented on commands/deployment.js
> +		.option('-mg, --mongo <mongo>', 'MongoDB URI')
We use both argument or environment variable.

2021-02-02 13:34 UTC, davidmeirlevy commented
@drorrose you didn't update the actual review..

2021-02-02 14:35 UTC, drorrose approved these changes
Looks good to me 🙂

2021-02-02 14:39 UTC, merged