feat: added a crude progress bar and a please wait message
greenpress/greenpress-cli pull request #59
Opened 2021-02-18 00:40 UTC by drorrose

2021-02-18 05:01 UTC, davidmeirlevy requested changes
The progress won't always work like that..

2021-02-22 17:24 UTC, drorrose commented
@davidmeirlevy 
Reimplemented version is ready for review!

2021-02-23 09:21 UTC, davidmeirlevy requested changes

2021-02-23 09:21 UTC, davidmeirlevy commented on controllers/start.js
> +	});
I would suggest to take that code that initialize greenpress, and put it in a separate function.
That function will build the args, run the spawn, subscribe to error, and return the process instance.

2021-02-23 09:21 UTC, davidmeirlevy commented on controllers/start.js
> +	}
This all area can be wrapped in a function.

2021-02-23 09:21 UTC, davidmeirlevy commented on services/start.js
> +let servicesCurrentValue = 0;
This file is too long, handles various of things and couples to different behaviors.
Separate the state and the progressBar management into different files.

2021-02-23 11:38 UTC, drorrose commented on services/start.js
> +let servicesCurrentValue = 0;
Done, created a separate utility file for it

2021-02-23 11:39 UTC, drorrose commented on controllers/start.js
> +	}
Done

2021-02-23 11:39 UTC, drorrose commented on controllers/start.js
> +	});
Done

2021-02-23 18:22 UTC, or-yam approved these changes

2021-02-24 09:11 UTC, davidmeirlevy approved these changes

2021-02-24 20:26 UTC, merged